### ISSUE TITLE
Add progress indicators

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/git-remote-dropbox#10]
It's somewhat difficult to have progress indicators for some things - for example, with the way we fetch objects, we don't know in advance how many we need to fetch.

Still, it would be nice to have some indication of progress while stuff is working.

With the current implementation, it's possible to pass `-vv` to the Git command to put the helper in verbose mode, and that prints a bunch of debugging output, but that's super noisy and not that nice to look at.

**Comment by arpit1997** [comment]
I can suggest some things about solving this issue which could be useful
As you said in your comment @anishathalye that git has verbose logs so we can parse these logs at the run time. This parsed data can be used for making a progress bar. There are some famous libraries for this purpose, [Progressbar](https://pypi.python.org/pypi/progressbar) is one of them. I guess this information is helpful to you. Ping me if there is any mistakes.
Thank you. :smile:

**Comment by anishathalye** [comment]
Oh so this was actually added in 666c083a234b42d40a614d06f2180e11c5640c19.

**Comment by arpit1997** [comment]
Really sorry for not seeing this commit https://github.com/anishathalye/git-remote-dropbox/commit/666c083a234b42d40a614d06f2180e11c5640c19 I thought that this issue is open and ready for discussion so i commented as per my understanding. Can you please try to close all the issues that are resolved or there is even a better way that mention that issue in the commit or PR so that we can get information about that the progress of issue.
:smile:

**Comment by anishathalye** [comment]
Yeah, it was just this issue, all other open issues are still open
