### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by PandaWhisperer** [anishathalye/git-remote-dropbox#23]
I just tried to get this working using a shared folder on Dropbox. I created a repo in that folder using `git init --bare`.

However, as much as I try, I can't get the dropbox remote to work. I keep getting this error:

```
error: exception while writing objects
error: failed to push some refs to 'dropbox://PacePro\ -\ Backups/GitHub/PacePro'
```

**Comment by anishathalye** [comment]
Hmm...

For one, you shouldn't be creating a bare repo on Dropbox (see https://github.com/anishathalye/git-remote-dropbox/issues/22#issuecomment-148544185). You can just push to a nonexistent directory on Dropbox and the helper will take care of everything.

Sorry that the error reporting is still bad (see #9). The issue here is that you're using a backslash (`\`) character in your remote path. You should `git remote set-url origin 'dropbox://PacePro\ -\ Backups/GitHub/PacePro'`.

Let me know if that helps.

**Comment by anishathalye** [comment]
Whoops, I meant to write `git remote set-url origin 'dropbox://PacePro - Backups/GitHub/PacePro'`

**Comment by PandaWhisperer** [comment]
Okay. Let me try that.

**Comment by PandaWhisperer** [comment]
If I've already created a bare repo (or possibly even pushed to it), is that a problem?

**Comment by anishathalye** [comment]
A bare repo on Dropbox, right? Just delete it.
The on-disk format used on Dropbox is [similar](https://github.com/anishathalye/git-remote-dropbox/blob/master/DESIGN.md#repository-layout) to Git's on-disk format, but it's not quite the same.

**Comment by PandaWhisperer** [comment]
Uh oh. I just pushed to it (after failing to make this tool work, I just did what all the other sites recommended a pushed to a locally synced folder). Looks like everything is fine though. 

I noticed this is taking much longer than pushing to a local directory (which makes sense, because the upload happens in the background in this case).

**Comment by anishathalye** [comment]
As explained [here](http://www.anishathalye.com/2015/08/19/git-remote-dropbox/), doing what all the other sites recommend isn't really the best way to do things. It can break in weird ways.

Yeah, this tool uploads stuff synchronously. It has to in order to behave like a true git remote (and offer real multi-user support).

**Comment by anishathalye** [comment]
I'm going to assume that this is resolved. If not, feel free to reopen the issue.
