### ISSUE TITLE
Does not push the files

### ISSUE THREAD

**Issue by photous** [anishathalye/git-remote-dropbox#27]
Hi, 
I have set everything up, but when I push to `origin master`.
The only thing that gets pushed are two folders `objects` and `refs`.
Here's everything that I did:
First I created a folder in dropbox named `tt`, then I ran the following commands:
```
mkdir tt
cd tt
touch file.txt
git init
git remote add origin "dropbox://tt"
git add .
git commit -m "Initial commit"
```
then pushing:
```
git push origin master
```
Here's the pushing output:
```
To dropbox://tt
 * [new branch]      master -> master

```

Everything is good, Now when I go to my Dropbox, I only see two folders in the `tt` folder the `objects` and `refs` folders (BTW what are those folders anyway?).
The main Issue is that the file `file.txt` (or any other files) were not pushed.

**Comment by anishathalye** [comment]
That's expected behavior. Maybe you're confused about what this extension is supposed to do? Taking a closer look at [notes](https://github.com/anishathalye/git-remote-dropbox#notes), [FAQ](https://github.com/anishathalye/git-remote-dropbox#faq), and [design doc](https://github.com/anishathalye/git-remote-dropbox/blob/master/DESIGN.md) might help clear things up.

Basically, you're not supposed to worry about the files in your `/tt` folder in your Dropbox -- you're not meant to use that folder directly, only through git-remote-dropbox.

Once you've done what you've done, you can go somewhere else on your computer (or another computer) and do `git clone dropbox://tt && git checkout master` and you should be able to see the `file.txt` file in there.

**Comment by photous** [comment]
Oh, thank you very much :smile: I did not actually understand what a git repo is; I thought it would be something like Github.
