### ISSUE TITLE
Investigate git-lfs support

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/git-remote-dropbox#28]
Dropbox is pretty good for hosting large files. It would be really cool if we could support something kind of like [git-lfs](https://git-lfs.github.com/) in git-remote-dropbox and provide a really nice seamless user experience.

**Comment by WeirdBeardDev** [comment]
Would like work with https://github.com/sinbad/lfs-folderstore?  I'm creating a game using Unity and I quickly blew through the free LFS on GitHub.  I want to split the lfs storage location off to a Dropbox folder.  I'm thinking a combo of git-remote-dropbox and lfs-folderstore may work.

**Comment by dklinges9** [comment]
@WeirdBeardDev thanks for pointing me in the direction of lfs-folderstore, it looks like this works. I only got things off the ground, however, if I referenced the filepath of a local version of the Dropbox folder when configuring the lfs-folderstore file, eg:, rather than referring to the remote version of the Dropbox folder itself. This still seems to sync across machines through Dropbox

**Comment by echuber2** [comment]
`~/Dropbox` would only work for different users on Mac and Linux though, right? This seems risky. I haven't even tried using git-remote-dropbox with multiple people concurrently.

**Comment by anishathalye** [comment]
Closing due to age.
