### ISSUE TITLE
is bare git on dropbox really a problem? [cf article]

### ISSUE THREAD

**Issue by timotheecour** [anishathalye/git-remote-dropbox#40]
http://edinburghhacklab.com/2012/11/when-git-on-dropbox-conflicts-no-problem/

**Comment by anishathalye** [comment]
Yes, it really is a problem. I've written a blog post about it [here](http://www.anishathalye.com/2015/08/19/git-remote-dropbox/).

In the single user case, with enough time between updates or with fast syncing, it is unlikely that you'll have problems that you can't recover from (as long as you understand git internals… you'll need to go mucking around in the `.git` folder). However, git-remote-dropbox was really built for the multi-user case -- to make it so that you can have a shared folder and then have multiple people concurrently using the "git server" safely. In the multi-user setting, just sticking a bare repository in Dropbox can actually result in data loss. Even in the single user setting, it's a lot nicer to use git-remote-dropbox, which just works, rather than using a method that kinda sorta works but might break at any time and require repair.

The article says:

> Every commit is stored in the subdirectory .git/objects under its SHA-1 hash. This means its extremely unlikely that the commit *data* will collide. Cool!

Yes. You're not going to have SHA1 collisions. But that's not the real problem. Saying "every [object] is stored in the subdirectory .git/objects under its SHA-1 hash" is only true to first approximation. Git's not that simple. It doesn't just store all the objects separately in the filesystem, each independently addressed by its SHA1. One thing it does is that it implements an optimization called [packfiles](https://git-scm.com/book/en/v2/Git-Internals-Packfiles). If multiple clients are packing files differently, this may do weird things when you synchronize. Also, git implements garbage collection to delete unreferenced objects. If multiple people push a ref, there's a conflicted copy created, and some changes are "lost" (hidden, but still there as loose objects), the associated objects can actually be _deleted_ as a result of garbage collection.

So yes, bare Git on Dropbox seems to work okay for the most part, except when it doesn't.

**Comment by anishathalye** [comment]
I'm assuming this is resolved, feel free to reopen if you have any other questions.

I guess this information would be good to put somewhere (maybe the wiki or something?), but I'm not going to do anything with it for now.
