### ISSUE TITLE
The Documentation is too tearse - also for Windows

### ISSUE THREAD

**Issue by haimivan** [anishathalye/git-remote-dropbox#48]
Hi,

for a beginner to git, it is quite difficult to understand how to setup git-remote-dropbox.
It would be very helpful, if a small tutorial would exist.

It remains unclear whether the code / my project has to be stored in a dropbox folder or whether the index is in the dropbox.

Additionally the user does not get an idea how much space is needed in the dropbox - additionally to the sole project files.

Thanks in advance.

**Comment by anishathalye** [comment]
The documentation in the README is pretty terse because it does assume that the user is somewhat familiar with Git. I'm not planning on writing my own Git tutorial - there are a lot of good resources on the Internet for that (e.g. https://git-scm.com/documentation).

The [design doc](https://github.com/anishathalye/git-remote-dropbox/blob/master/DESIGN.rst) should do a pretty good job of answering your question on how things are stored.

You can see how much space a repository is taking up in your Dropbox by just checking the size of the folder on Dropbox. To get an estimate, you could run this command in your repo:

```bash
git rev-list --objects --all | awk '{print $1}' | xargs -L 1 -I % sh -c 'git cat-file $(git cat-file -t %) % | gzip | wc -c' | awk '{ sum += $1 } END { print sum }'
```

If you have any ideas on how the documentation in the README could be made more clear, contributions would be appreciated!

**Comment by haimivan** [comment]
Hi!

1. replace:
pip install git-remote-dropbox
with
sudo pip install git-remote-dropbox

2. Put the "Setup" at the beginning, afterwards the typical use cases.

3. perhaps give an example for the usual workflow/typical use cases....
This could be something like:
a) clone a repository from an "official" github project.
   `git clone https://github.com/anishathalye/git-remote-dropbox.git`
b) add this to the dropbox git:
`cd git-remote-dropbox`
`git remote add origin "dropbox://arbitrary-non-existing-folder"`

.......
And by the way, the last command leads to the following error:
`fatal: remote origin already exists.`

(and the folder `arbitrary-non-existing-folder` does not exist...)
How could I solve this?

**Comment by anishathalye** [comment]
1. The decision of whether or not to use `sudo` depends on how your Python/Pip is set up, so it doesn't make sense to have the documentation say that using `sudo` is necessary.

2. I think it's good to show how a tool is used as early as possible in the REAMDE (so people can see if a tool suits their use case). And the sections are so small that I don't think reordering makes a big difference.

3. Yes, that could be helpful, but that's just documentation on how git remotes work (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) -- it's nothing special about git-remote-dropbox. You get the error message `fatal: remote origin already exists` if you already have a remote with the name `origin`. If you create the remote with any other name, it'll work. And the folder doesn't need to exist on Dropbox - git-remote-dropbox will create it for you.

**Comment by anishathalye** [comment]
Going to close for now, feel free to reopen if anything new comes up.
