### ISSUE TITLE
Odd new API error

### ISSUE THREAD

**Issue by astoeckley** [anishathalye/git-remote-dropbox#58]
Most of my repos are working fine, but I have one that is attempting to download the wrong branch (I think) when I fetch, it doesn't attempt to fetch from the current working branch, and it reports an API exception:

(I have replaced here some long character sequences with xxxxx since I wasn't sure if they were sensitive.)

```
git fetch
error: exception while downloading: ApiError('xxxxxxxxxxxxxxxxxxxxxxxxxx', DownloadError(u'path', LookupError(u'not_found', None)))
```

Also:

```
GIT_TRANSPORT_HELPER_DEBUG=1 git fetch
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Capabilities complete.
Debug: Remote helper: -> option progress true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> option verbosity 1
Debug: Remote helper: Waiting...
Debug: Remote helper: <- ok
Debug: Remote helper: Waiting...
Debug: Remote helper: <- xxxxxxxxxxxxxxxxxxxxxxxxx refs/heads/master
Debug: Remote helper: Waiting...
Debug: Remote helper: <- xxxxxxxxxxxxxxxxxxxxxxxxx refs/heads/imac
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Read ref listing.
Debug: Remote helper: -> option followtags true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> fetch xxxxxxxxxxxxxxxxxxxxxxxxx refs/heads/master
fetch xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx refs/heads/imac

Debug: Remote helper: Waiting...
error: unexpected exception
Debug: Remote helper quit.
```

However if I do this explicitly, it works:

git fetch origin master

It appears to be tracking the correct remote branch:

```
git status
On branch master
Your branch is ahead of 'origin/master' by 12 commits.
```

Also ```git push``` works fine.

Any idea?

**Comment by anishathalye** [comment]
Looks like the remote is missing objects (but this shouldn't be possible).

Is `imac` some invalid branch? You can delete it on the remote using `git push origin :imac`, and then everything should work fine.

But there never should have been a branch in an invalid state on the remote...

**Comment by astoeckley** [comment]
The imac branch is valid. On a different machine, which syncs only to that imac branch, I have the same problem, but it fetches if I explicitly say ```git fetch origin imac``` so both branches appear to be working, but only if I explicitly say which branch I'm fetching from.

I do not want to delete the imac branch, I use it.

Strange scenario indeed. It sounds like the remote repo somehow got corrupted. I do this sort of per-machine branching with other repos hosted elsewhere (not on Dropbox) and have never encountered this.

**Comment by anishathalye** [comment]
Wow, that's really weird. This does seem like something is wrong -- the remote repo may be missing objects that are in the `imac` branch. And if you fetch on the machine that already has the `imac` branch, it doesn't try to re-fetch the objects it already has, so it seems to work.

What if you explicitly `git fetch origin imac` on the first machine? Does that fail? Or if you do a fresh clone and then `git fetch origin imac` -- does that fail?

**Comment by astoeckley** [comment]
Here are some things I tried:

A fresh clone:

```
Receiving objects:  99% (134/135)error: exception while downloading: ApiError('xxxxxxxxxxxxxxxxxx', DownloadError(u'path', LookupError(u'not_found', None)))
```

On machine 1 which uses master, I get the same error:
```
git fetch origin imac
error: exception while downloading: ApiError('de0dbe2c0f4e69ffc32000add82a164c', DownloadError(u'path', LookupError(u'not_found', None)))
```

On machine 2 which uses the imac branch, also the same when doing ```git fetch origin master```.

If each machine explicitly fetches the branch it uses, no problems.

**Comment by anishathalye** [comment]
So it does seem like that Git object is missing from your repository on Dropbox. I have no idea how it happened (it shouldn't be possible according to the [design](https://github.com/anishathalye/git-remote-dropbox/blob/master/DESIGN.rst) - we upload all objects before updating the ref)...

For now, here's a fix. First, run the same command, but with `-v`. So like `git clone -v dropbox://bla`. You'll see something like

```
<stuff>
debug: fetching: /repos/test/objects/1c/e5c11d29fcfcaf7a77671164938c3975c8560c
error: exception while downloading: ('<garbage>', DownloadError(u'path', LookupError(u'not_found', None)))
```

That'll help you identify your missing object. You should see that it's missing in your Dropbox if you go to `/bla/objects/{first two characters, e.g. 1c}` and look for a file named `{rest of the characters e.g. e5c11d29fcfcaf7a77671164938c3975c8560c}`.

You can fix it by doing the following from one of your repos that has the missing object, using a Python shell:

```python
import git_remote_dropbox
open('missing', 'w').write(git_remote_dropbox.git_encode_object('1ce5c11d29fcfcaf7a77671164938c3975c8560c'))
```

Now, take the file called `missing`, rename it to `e5c11d29fcfcaf7a77671164938c3975c8560c`, and put it in your Dropbox, in `/bla/objects/1c/e5544c665136473e32b50c37dddec40c` (of course, using your SHA1 instead of mine - it's a directory named by the first two characters, and the file is named using the rest of the characters).

Or you could delete your repo from Dropbox and re-push the whole thing.

---

I'm really curious why this is happening -- I've never encountered a situation like this before. Do you think the object file could have been accidentally deleted from your Dropbox?

**Comment by astoeckley** [comment]
Thanks for the help, and perhaps your notes will be useful for anyone else who might encounter this issue in the future.

I do not know why or how this happened, but it does make me feel good that I have only used DB for repos that are not too important for me.

In the interests of time, I shall opt for your second suggestion if just deleting the repo from DB and doing that over again. I'm not much of a Python guy and don't have a lot of time to work on the fix.

But thanks for your attention to this matter!
