### ISSUE TITLE
Support shallow cloning

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/git-remote-dropbox#7]
Currently, we don't support shallow cloning. It's worth investigating to see if it's possible to do this without too much work.

**Comment by anishathalye** [comment]
Closing due to age. (Also, it doesn't seem like there is demand for this.)

**Comment by pjcrosbie** [comment]
shallow clone is very useful for repos that have large (or many) artifacts/blobs which git stores changes to as entirely new files rather than as file differences. over time these repos can get quite large if there are many edits to the artifacts/blobs. repos with these characteristics are common for documentation or research paper focused projects

creating a shallow clone can be very convenient way to speed up cloning a repo with these characteristics when you just need the latest version

it would be wonderful if you could add shallow clone to support this, many thanks

**Comment by anishathalye** [comment]
Happy to keep this open, but it's unlikely that I'll have time in the near future to work on this. Happy to accept a PR.

**Comment by pjcrosbie** [comment]
got it, thx

**Comment by anishathalye** [comment]
Again, closing due to age. I am not planning on implementing this, and no external contributor has gotten to it in 9 years 🙃
