### ISSUE TITLE
Multiple-user tutorial

### ISSUE THREAD

**Issue by ETaSky** [anishathalye/git-remote-dropbox#94]
Hello,

Thank you for the great app. I am able to set-up git with dropbox for myself using the README and wiki tutorial. But I wonder if you could create a tutorial for multi-use case. The reason I asked is because I am not sure how I can share the dropbox remote repository with a colleague. Right now, the remote repository is under Dropbox/Apps/my-app/project/. Should we just share the project folder with another people? 

Thanks!

Jincheng

**Comment by anishathalye** [comment]
Yes, just share the project folder, and have the collaborators access it using git-remote-dropbox as well.

**Comment by echuber2** [comment]
I'd remind the people you share it with that they shouldn't let the Dropbox desktop app sync the repo directory. I've never tried using this to collaborate on a repo with other people... interesting to know that this is even recommended.

**Comment by anishathalye** [comment]
Not just recommended, it's what git-remote-dropbox was designed for :)

> After adding the remote, you can treat it just like a regular Git remote. The Dropbox-backed remote supports all operations that regular remotes support, and it provides identical guarantees in terms of atomicity even when there are concurrent operations, even when using a shared folder.

**Comment by ETaSky** [comment]
Thanks @echuber2 and @anishathalye ! I think this is where it is getting quite confusing. Let me explain:
(1) In order to use git-remote-dropbox, we need to request an API access to Dropbox. Basically one will create a personal connected app to Dropbox (in my case the app name is jw-git). When we `git remote add origin "dropbox:///path/to/repo"`, it actually add the repo under Dropbox/Apps/jw-git/repo. In other word, it is under the personal app directory I created. Would that be a problem if I share a folder under my personal app directory? Would my colleague be able to push or pull from that folder?
(2) For my colleague, again in order to use git-remote-dropbox, he/she will create a personal connected app to Dropbox. But since the repo is under my app, it seems that the step of creating his/her own app is not necessary.
(3) For git to the Dropbox remote, I have to use my token for that personal app, but how my colleague will be able to pull or push to it if he/she doesn't have my token, or should I share the token with him/her as well?

In the end, people may wonder, why don't you just use github/bitbucket to do this. The main reason for me is that I am a biologist who is analyzing some sequencing data. I am trying to use version control because there are a lot of back-and-forth with how the data should be analyzed, and I don't want to create a million different copies of my analysis code. Meanwhile, analyzing sequencing data would generate intermediate and output files (e.g. dataset or figures) that are too big and many to sync with github server. I really don't see a good solution for this kind of niche applications.

Thanks!

**Comment by echuber2** [comment]
I suppose Anish will answer too and I don't want to take up a lot of space here, but this is what I do. I created a folder in my Dropbox account called `gitsafe` which is where I put all repos. Then, I explicitly mark `gitsafe` as *not synced* by the Dropbox app on any computer I have, using the selective sync feature. So the `gitsafe` directory does not show up in my Dropbox folder under my home directory locally. However, the `git-remote-dropbox` program can still use these remotes on the Dropbox server through my account token. Since *all* of the remotes I create are under `gitsafe`, I only had to deal with selective sync once per machine I set up initially (to mark `gitsafe` not-synced).

Your colleague would have to accept the share of the repo folder, mark it *not synced* in the Dropbox desktop app, and then interact with it *only* as a git remote. Since the folder is shared with your colleague's Dropbox account, your colleague can use their own credentials to interact with it. Do *not* give them your credential token. I'm pretty sure that's a huge security risk to your account.

I do think you could use plain old GitHub or etc. for this, though. Git itself has weaknesses for large binary data regardless of your hosting solution, even using this app. For that reason there is git-lfs:

https://git-lfs.github.com/

But this costs a surcharge to use on GitHub so that may be a good reason to use the Dropbox solution. I haven't looked at how the price scales competitively.

Also, you can use `.gitignore` files to mark all those intermediate and temporary files not tracked by git at all.

**Comment by ETaSky** [comment]
Thanks @echuber2 ! This makes a lot of sense. And I guess to use the `gitsafe`  solution, I would need to select that "Full Dropbox" access instead of "App Folder", and so would my colleague. 

And thank you very much for your suggestions related to git-lfs. I'll check it out. At this moment, as long as the git-remote-dropbox solution works for me, I'll stick with dropbox because I have nearly 1 TB data/files synced with dropbox now. Meanwhile, I do hope dropbox would provide better solutions because I think all the infrastructure are there (Dropbox version history).

Thanks!

**Comment by mzbik** [comment]
> Yes, just share the project folder, and have the collaborators access it using git-remote-dropbox as well. They'll have to create their own token. The path might also look different for them (wherever the shared folder appears for them in _their_ Dropbox).

"They'll have to create their own token": do you mean they need to go and create their own dropbox app and generate a token?

**Comment by anishathalye** [comment]
> "They'll have to create their own token": do you mean they need to go and create their own dropbox app and generate a token?

Yes, that is correct.

**Comment by anishathalye** [comment]
Fixed by #98.
