### ISSUE TITLE
'remote-dropbox' is not a git command

### ISSUE THREAD

**Issue by smalltext** [anishathalye/git-remote-dropbox#95]
Receiving "git: 'remote-dropbox' is not a git command. See 'git --help'." upon trying to clone remote repos. This wasn't occurring a few weeks ago, so it may be a problem on my end. Regardless help is appreciated.

OS: Windows 10 64-bit.
Git version: 2.27.0.windows.1
git-remote-dropbox version: 1.1.2, also occurred with 1.1.1.

Tried uninstalling and reinstalling git-remote-dropbox, updating git, updating pip, and disabling Microsoft store python installs. Cloning from github remotes still works fine, so it's remote-dropbox specific. I've tried with repos in separate dropboxes with separate tokens to the same error.

Has anyone else had this issue?

**Comment by echuber2** [comment]
The error message is saying that "remote-dropbox" is not a subcommand that `git` accepts, which is true. Please look over the instructions and example usage: https://github.com/anishathalye/git-remote-dropbox

**Comment by echuber2** [comment]
Sorry, I need to correct my last comment: it appears that when you try to invoke `git remote-dropbox` (one hyphen), git will automatically search for an executable script called `git-remote-dropbox` (two hyphens) in your system paths. However, you don't normally have to invoke it this way yourself.

If the issue is that you don't have `git-remote-dropbox` installed in your path, you may need to copy the script manually to an existing system path, or add the directory where `git-remote-dropbox` already is located to your system paths.

Here's how you can add executable search paths on Windows:
https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by anishathalye** [comment]
Yes, it seems like a $PATH issue, not something specific to git-remote-dropbox. Wherever pip is putting the programs is not in your search path. (If the program can be found in the search path, and you run `where git-remote-dropbox`, it will show you where it is.)

**Comment by smalltext** [comment]
I didn't actually invoke remote-dropbox. I just ran git clone, but I assume that running git clone with a dropbox link ends up invoking remote-dropbox.

You were right! It was an issue with the $PATH. Now everything is working, thanks for the help!

**Comment by anishathalye** [comment]
When you `git clone` from a `foo://` URI, it looks for a remote helper `git-remote-foo` (so in this case, `git-remote-dropbox`), and it tries to find it in the search path.
